### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Axkaban** [gregorysgeorge/teacozy#1]
Great work! 
Thank you for the comments [https://github.com/gregorysgeorge/teacozy/blob/master/index.html#L21](https://github.com/gregorysgeorge/teacozy/blob/master/index.html#L21)

Good use of ids and classes with related names [https://github.com/gregorysgeorge/teacozy/blob/master/index.html#L24-L25](https://github.com/gregorysgeorge/teacozy/blob/master/index.html#L24-L25)

You have the `alt` attribute but it is empty [https://github.com/gregorysgeorge/teacozy/blob/master/index.html#L37](https://github.com/gregorysgeorge/teacozy/blob/master/index.html#L37)
it becomes important in case your image file breaks or the link is no longer available. Thus if that was the case `alt= 'container of loose leaf tea'` will at least give an idea to what the image is about.

**Comment by gregorysgeorge** [comment]
Hi Axel,
thank you for the review. 

Have a nice day,
Giorgio

**Comment by Axkaban** [comment]
No problem! Have a good one as well!
